### ISSUE TITLE
[Request] Move away from Python2 and support plotting via Python3

### ISSUE THREAD

**Issue by acxz** [ethz-adrl/control-toolbox#102]
As you may know, python.org has stopped supporting python2, and even though Canonical has picked up supporting python2 for the time being, it is probably a good idea to move towards a plotting codebase that works with Python3.

**Comment by markusgft** [comment]
Good point, I agree that should be tackled at some point!

**Comment by acxz** [comment]
I'm gonna leave this here since I think it relates. https://pybind11.readthedocs.io/en/stable/advanced/embedding.html

TLDR we embed python interpreter and use it for plotting. Here we can get full feature parity (since we are using python directly, instead of wrapping it) compared to matplotlib-cpp. We can also use different and better plotting libraries like [plot.ly](https://plotly.com/python/) instead of matplotlib.

Here is an example repo with this: https://github.com/tttapa/Pybind11-Matplotlib-Cpp
