### ISSUE TITLE
Cost function with higher order state derivative terms

### ISSUE THREAD

**Issue by rshum19** [ethz-adrl/control-toolbox#124]
Hi 

I was wondering if there is a way of using higher order derivative of the state in the cost function? For example for a quadrotor we would like to minimize the snap. So far I have only found how to implement state based  quadratic cost function. 

Thank you!

**Comment by markusgft** [comment]
Dear @rshum19 
No, this functionality is currently not implemented. But due to the modular structure of the cost functions and terms, it should be relatively straight-forward to create a custom term with the higher-order derivatives that you need!
Best
