### ISSUE TITLE
Upgrade to newest version of HPIPM/Blasfeo

### ISSUE THREAD

**Issue by markusgft** [ethz-adrl/control-toolbox#13]
* in oder to avoid the issue that ct-v2 hpipm and blasfeo versions do not provide an installation routine. Exporting dependencies is therefore not solid.

To check:
- [ ] licensing issues may occur. The current releases of hpipm and blasfeo are GPL 3.0, while our currently used version was released under L-GPL.

**Comment by jcarius** [comment]
@rubengrandia might be of help here

**Comment by markusgft** [comment]
> @rubengrandia might be of help here

@rubengrandia would you be interested in committing this feature? It would be highly welcomed and would be a great contribution.

**Comment by rubengrandia** [comment]
Updating to the lastest hpipm + blasfeo is still something I want to do and updating it in the CT would be a good first step. However, it is unclear when I will have time for this.

With licensing I am less familiar and is probably more relevant for you and Michael.

**Comment by markusgft** [comment]
I have gotten the newest hpipm-release to work with the CT. I will commit this soon and notify everyone.
