### ISSUE TITLE
Derivatives of class LTISystem do not compile because of flawed function override

### ISSUE THREAD

**Issue by schulz0r** [ethz-adrl/control-toolbox#143]
Dear developer team,
I use Apple clang version 11.0.3 and cannot compile following code:
```
class Model: public ct::core::LTISystem<6, 3> {
    Model(): ct::core::LTISystem<6, 3>(Eigen::MatrixXd::Zero(6,6), Eigen::MatrixXd::Zero(6,3)) {}
};
```
The reason is that the class `LTISystem` incorrectly overrides the virtual functions getDerivativeState() and getDerivativeControl() which originally stem from the parent class `LinearSystem`.
The code of `LTISystem.h` shows that the return type is `Eigen::Matrix`, but the compiler expects the types to be `StateMatrix` and `StateControlMatrix`. They might be the same inherently, but the compiler does not accept that.

**Comment by markusgft** [comment]
Dear @schulz0r , this had been reported in #86, too. However, at that point in time, we fixed it only for the devel-branch. Since the issue was raised again for v3.0.2, I will look into this and commit a fix as soon as I find time.

**Comment by markusgft** [comment]
Please check if it works for your now!

**Comment by schulz0r** [comment]
My code compiles now! Thanks for the quick response!
