### ISSUE TITLE
Cannot find blasfeo headers because CMake does not include them despite finding blasfeo

### ISSUE THREAD

**Issue by schulz0r** [ethz-adrl/control-toolbox#148]
Dear developers,
I downloaded hpipm and blasfeo from their respective git repositories here on Github and built/installed them on my machine. When compiling the Control Toolbox with the optimal control addon, I encounter the problem that blasfeo_target.h cannot be found. **The problem could be solved** when changing line 66 in ct_optcon/CMakeLists.txt from:

`list(APPEND HPIPM_LIBS ${hpipm_LIBRARIES} ${blasfeo_LIBRARIES})`
to:
`list(APPEND HPIPM_LIBS hpipm blasfeo)`

CMake does not require you to add `${<name>_LIBRARIES}` and `${<name>_INCLUDE_DIRS}` to link against dependencies or include their headers. Just link the target created by `find_package()`, this will also include all headers. I believe that this way is less error prone and should be preferred.

Edit: I did not encounter any problem with this, but int ct_core/CMakeLists.txt you added the Python libraries with `${Python_LIBRARIES}` and `${PYTHON_INCLUDE_DIRS}`. You can simply link against `Python::Python` according to [this page in the CMake manual](https://cmake.org/cmake/help/git-stage/module/FindPython.html).

**Comment by acxz** [comment]
I agree with this. The `_LIBRARIES` and `_INCLUDE_DIRS` variables are legacy methods of handling deps. I'll see if I can reproduce the error with the latest hpipm and blasfeo and come up with a solution.

@schulz0r Using the latest blasfeo and hpipm I was not able to reproduce this error. Can you try again and post the exact error you received? Although I don't get an error using `hpipm` and `blasfeo` targets either.

**Comment by acxz** [comment]
re: python, we want to stay on a lower minimum cmake version to support legacy operating systems which is why we cannot link against the `Python:Python` target. Once we raise our min cmake version we will be sure to update that as well.

**Comment by acxz** [comment]
@schulz0r if you could test out the linked PR and confirm that it resolves the issue for you that would be great. Thx for reporting.

**Comment by schulz0r** [comment]
I just want to tell that I have seen your PR and I will check it out this week.

**Comment by schulz0r** [comment]
I checked it out and it worked for me. Thanks a lot!

**Comment by acxz** [comment]
Glad to hear!
