### ISSUE TITLE
How to find a feasible path given sequence of points.

### ISSUE THREAD

**Issue by Shantnu12345** [ethz-adrl/control-toolbox#162]
Hi,

Thank you for sharing this. This is really helpful for researchers and kudos to your hard work. I am wondering if can this library be used for the following usecase and how to use it for the following usecase:

**Given a sequence of points in 2D cartesian coordinate** (each point is represented as (x,y))**, generate a feasible path** (each point in path is (x, y, yaw, steering angle)) **for an ackerman steering vehicle** (with kinematic constraints like max steering angle). **The path should ideally pass through all the points but if going through some points is not feasible then it tries to go as close as possible through those points.** The start position of the vehicle is the first point in the sequence and start orientation is in the direction from first point to second point in the sequence . The velocity of the vehicle is an input and considered to be constant throughout the path. Obstacles can be ignored in the scene. Please note that this is just path planning problem, not a real time controls problem. So, the path needs to be found just once and that path is the output.

Please note: My usecase is similar to this: https://github.com/mohamedbanhawi/ReceedingHorizonControlAutonomousVehicle, Their code, however, doesn't seem very robust and I am getting weird results.

It would be really helpful if you could direct me in the right direction how to solve this problem using this library (if possible) or using some other technique beyond the scope of this library.

Best,
Shantnu

**Comment by markusgft** [comment]
Dear Shantnu,

thanks for message, and sorry for not getting back to you earlier.

I am afraid there is no out-of-the-box solution for your problem 
available in the control toolbox. The problem you are describing 
involves constraints that are not trivial to handle. If you want to give 
the problem a shot using the control-toolbox, I would recommend you the 
following strategy:

- eliminate your differential constraint from the system by formulating 
the system dynamics accordingly (lower-dimensional control input that 
matches the physical control input to the system, but probably you have 
already done that).

- for the sake of simplicity, I would remove the max-steering angle 
constraint for the time being, and only add it back later once you have 
validated that you get solutions for a simpler problem.

- we do currently not support time-optimal control. Hence, I would 
recommend you to assign a reference time (desired passthrough-time) to 
every waypoint, and formulate a cost function where the intermediate 
cost includes quadratic terms for the waypoints that are being activated 
using smooth, time-dependent "activation functions".

- use iLQR to solve this problem.

- This will not guarantee you to meet waypoints with a predefined 
accuracy, but with a bit of tuning, this should lead to pretty nice results.

- bring back your constraints, ideally by modelling them as box 
constraints if somehow possible, and use hpipm as constrained optimal 
control solver.

I hope this helps!

Markus
