### ISSUE TITLE
UAV/Drone MPC path traking controller example 

### ISSUE THREAD

**Issue by dookei** [ethz-adrl/control-toolbox#180]
Hi there, I would lov to use this package in a Drone/UAV simulation under ROS. Like shown in the demonstration videos.  Could anyone please give me some guidance where I should start?
What actuators should be controlled( position or velocity or acceleration or Roll, pitch, Yaw?)
The basic theory behind MPC I believe I got it(at least I like to think so ;-).

**Comment by markusgft** [comment]
Hi @dookei,
I would recommend you to start by looking at the following example that we provide it ct_ros, see https://github.com/ethz-adrl/ct_ros/blob/master/ct_ros_nodes/examples/Quadrotor/QuadrotorNLOC.cpp
This performs trajectory optimization for a quadrotor. From there, it should be relatively easy to go for unconstrained MPC, by running iLQR or GNMs iteratively.
Best!

**Comment by dookei** [comment]
Hi @markusgft , thank you very much for your prompt reply.  I will look into it and try it out.
