### ISSUE TITLE
Using FHDTLQR for trajectory tracking

### ISSUE THREAD

**Issue by rokasgie** [ethz-adrl/control-toolbox#181]
I have been trying to use the FHDTLQR for trajectory tracking but I was not able to find any examples or tutorials on that. Is there any material available? Also, would there be a way of using box constraints in such a problem?

**Comment by markusgft** [comment]
Dear @rokasgie 
Thanks for your interest in this toolbox. 
No, unfortunately we currently do not have a unit test or example for the finite horizon time-varying LQR.
There is an example for the infinite horizon LQR controller, see ct_optcon/examples/LQR.cpp
The use of the time-varying version would be similar, you only have to provide trajectories of states, controls, and A & B matrices to the designController() method.
Best!
