### ISSUE TITLE
Test HPIPM solver failed

### ISSUE THREAD

**Issue by huakang402** [ethz-adrl/control-toolbox#187]
Hello!
I encountered the following problem when using HPIPM solver to solve a constrained system, but I ran the example (NLOC_boxConstrained.cpp) successfully.

![11111](https://user-images.githubusercontent.com/60544760/111069461-20b69000-8508-11eb-8836-33ee33b7e10f.png)

**Comment by markusgft** [comment]
Hi, you are likely on the wrong version of hpipm.
Did you use the provided install script in ct/ ?
Best

**Comment by huakang402** [comment]
I reinstalled hpipm using the script in ct, and the problem was solved.
Thank you very much!
