### ISSUE TITLE
control input parametrization

### ISSUE THREAD

**Issue by awa152** [ethz-adrl/control-toolbox#189]
Hi, just a quick question from my side. 
The default control input parametrization is zero order-hold (assumption of constant control input between two discrete control steps), is there a way to switch to a linear parametrization?

Best regards

**Comment by markusgft** [comment]
Depends on the solver. Ilqr and gnms only support zoh.
The Independent Direct Multiple shooting solver, which is also available in the ct, also supports pwl.

**Comment by awa152** [comment]
Thank you for the fast response!
