### ISSUE TITLE
Can you share some control_tool in robotics?

### ISSUE THREAD

**Issue by csufangyu** [ethz-adrl/control-toolbox#194]
Hi,I have read all tutorials at [documentation](https://ethz-adrl.github.io/ct/ct_doc/doc/html/pages.html) and examples in project,such as [rbd_example](https://github.com/ethz-adrl/control-toolbox/tree/v3.0.2/ct_rbd/test/robot) I find there not tutorials about robotics in optcon.

 Can you share some tutorials about robotics in optcon? Thanks very much!

**Comment by markusgft** [comment]
Please take a look at https://github.com/ethz-adrl/ct_ros, hope this helps!

**Comment by csufangyu** [comment]
Thanks very much for your reply. Although you are very busy at google, you are still maintaining this project and helping us. Thank you very much for your contribution,again!
