### ISSUE TITLE
matplotlib import error

### ISSUE THREAD

**Issue by Zcyyy** [ethz-adrl/control-toolbox#204]
Error occurs when I run the “rosrun ct_core plotTest” command.
```
~/ct > rosrun ct_core plotTest                                   08:12:03
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error loading module matplotlib.pyplot!
[1]    27682 abort (core dumped)  rosrun ct_core plotTest
```
I have tried some methods，but There is no effect.

**Comment by markusgft** [comment]
Likely some version mismatch!

**Comment by Zcyyy** [comment]
@markusgft Thanks a lot. I run it successful when i change matplotlib version.

**Comment by NisharnSP** [comment]
> @markusgft Thanks a lot. I run it successful when i change
what matplotlib version did you use?

**Comment by Wow-zheng** [comment]
> > @markusgft Thanks a lot. I run it successful when i change
> 
> what matplotlib version did you use?

Did you solve the problem, thanks for your reply

**Comment by Wow-zheng** [comment]
After testing, the solution is as follows:
Ubuntu18.04
Python3.69
matplotlib3.0.2
