### ISSUE TITLE
Missing identifier ''i'

### ISSUE THREAD

**Issue by roversch** [ethz-adrl/control-toolbox#82]
I'm getting following compiler error when building examples:

    <...>/ct_optcon/examples/KalmanDisturbanceFiltering.cpp:316:63: error: ‘i’ was not declared in this scope
           << std::fixed << std::setprecision(6) << states[i][0] << "\t" << states_est[i][0] << "\t"`

A quick check shows indeed that 'i' is not declared if printing is disabled.

**Comment by markusgft** [comment]
@roversch thanks for reporting!
Fixed in #83
